### ISSUE TITLE
bosh deployment <deployment> - wrong director UUID

### ISSUE THREAD

**Issue by JamesClonk** [cloudfoundry-incubator/bosh-workspace#56] opened 2015-05-11 11:23 UTC
It seems that when running a `bosh deployment <deployment>`, bosh workspace is reading from .deployments/* and if it finds a file there it's using the director UUID from there, instead of the one configured in deployments/*.

In the sample case below the correct UUID would be 51e8dfeb-1de4-4cf5-abb1-b39e08673f56, as configured in `deployments/cf.yml`.
But because it found a (presumably old) file `.deployments/cf.yml` it picked the UUID from there, which was wrong.

```
$ cat deployments/cf.yml
---
name: my-cf
director_uuid: 51e8dfeb-1de4-4cf5-abb1-b39e08673f56
...
```

```
$ bundle exec bosh deployment cf
This manifest references director with UUID 8a88decc-b7b9-4533-975d-9cd8a20c9c3c.
You've never targeted it before.
Please find your director IP or hostname and target it first.
```

```
$ cat .deployments/cf.yml
---
director_uuid: 8a88decc-b7b9-4533-975d-9cd8a20c9c3c.
# Don't edit; placeholder deployment for: /home/user/bosh-workspace/deployments/cf.yml
```

**Comment by rkoster** [comment] 2015-05-29 17:44
duplicate of https://github.com/cloudfoundry-incubator/bosh-workspace/issues/21

**Closed by rkoster** 2015-05-29 17:44 UTC
